version: '2'
services:
  grid1:
    build:
      context: ./
      dockerfile: Dockerfiles/local
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - /var/www/vendor
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DB_HOST=host.docker.internal
      - DB_PORT=3308
      - DB_DATABASE=grid
      - DB_USERNAME=root
      - DB_PASSWORD='password'
    ports:
      - 8000:80
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'grid'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3308:3306
